version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-20.04
    ports:
      - "${DB_PORT}:1433"
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sql_data:/var/opt/mssql

  fileuploadapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-5201}:5201"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - sqlserver

volumes:
  sql_data:
